title: Yengin Loay
url: "https://LoayYengin.github.io"
# logo: /assets/img/logo.png
description: yengin.loay@gmail.com | Winnipeg, MB 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
